spring:
  application:
    name: analytics-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-service-group
      auto-offset-reset: earliest

server:
  port: 8082

logging:
  level:
    de.denizaltun.analyticsservice: DEBUG
    org.apache.kafka: WARN